networks:
  proxy:
    name: fursona
    ipam:
      driver: default
      config:
        - subnet: 192.168.90.0/24

volumes:
  mongodb_data:

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile_mongodb
    container_name: mongodb
    hostname: mongodb
    restart: always
    networks:
      - proxy
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:123456@mongodb:27017/test?authSource=admin&replicaSet=rs0&retryWrites=true&w=majority&directConnection=true"
    depends_on:
      - mongodb
    networks:
      - proxy

  fursona:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fursona
    restart: always
    depends_on:
      - mongodb
    networks:
      - proxy
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      SECRET: ${SECRET}
      MONGO_HOST: mongodb
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_SESSION_SECRET: ${MONGODB_SESSION_SECRET}
      SESSION_TTL: ${SESSION_TTL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SECURE_COOKIE: ${SECURE_COOKIE}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      AUTO_INDEX: ${AUTO_INDEX}
